repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.4
  hooks:
  - id: clang-format
    args: [--style=file, -i]
    #  - id: clang-tidy
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.10
  hooks:
  - id: cmake-format
